PY = python3
VENV = myenv
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
AUX = *.pyc *.cprof */*.pyc

install:
	$(PY) -m venv $(VENV)
	$(PIP) install pandas pycryptodome scipy matplotlib
	$(PIP) install -e ../../NTT/assets/pythonref/

test:
	$(PYTHON) test.py

test_keccak_prng:
	$(PYTHON) -m unittest test_keccak_prng

test_recovery_mode:
	$(PYTHON) -m unittest test_recovery_mode
	
profile:
	rm -f $(AUX)
	rm -rf __pycache__
	touch profile_action.cprof
	$(PY) -m cProfile -o profile_action.cprof profile_action.py
	pyprof2calltree -k -i profile_action.cprof &

clean:
	rm -f $(AUX)
	rm -rf __pycache__ */__pycache__
	rm -rf scripts/*.sage.py
	@echo "Clean done"
