# This Makefile compiles the implementation in this directory along with
# the known answer tests generator located in the
# ../../../KAT/generator/ directory. The output is an executable program
# in the build/ subdirectory, whose name starts with 'kat', followed by
# the implementation name (e.g. 'kat512int' for the 'falcon512int'
# implementation). This program, when executed, generates the .req and
# .rsp files in the expected NIST format.

.POSIX:

CC = gcc
CFLAGS = -W -Wall -O2 -DALGNAME=falcon512int
LD = gcc
LDFLAGS = 
LIBS = 

OBJ1 = build/codec.o build/common.o build/fft.o build/fpr.o build/keygen.o build/nist.o build/nist16.o build/epervier16.o build/rng.o build/shake.o build/sign.o build/vrfy.o

OBJ2 = build/PQCgenKAT_sign.o build/katrng.o
OBJ3 = build/PQCgenKAT_sign_zknox.o build/katrng.o
OBJ4 = build/PQCgenKAT_sign_epervier_zknox.o build/katrng.o

HEAD1 = api.h fpr.h inner.h
HEAD2 = api.h ../KAT/katrng.h

all: build build/kat512int build/kat512int_zknox build/kat512int_epervier_zknox

build:
	-mkdir build

clean:
	-rm -f build/kat512int build/kat512int_zknox build/kat512int_epervier_zknox $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4)
	-rm -f *.rsp *.req
 
build/kat512int: $(OBJ1) $(OBJ2)
	$(LD) $(LDFLAGS) -o build/kat512int $(OBJ1) $(OBJ2) $(LIBS)

build/kat512int_zknox: $(OBJ1) $(OBJ3)
	$(LD) $(LDFLAGS) -o build/kat512int_zknox $(OBJ1) $(OBJ3) $(LIBS)

build/kat512int_epervier_zknox: $(OBJ1) $(OBJ4)
	$(LD) $(LDFLAGS) -o build/kat512int_epervier_zknox $(OBJ1) $(OBJ4) $(LIBS)

build/codec.o: codec.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/codec.o codec.c

build/common.o: common.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/common.o common.c

build/fft.o: fft.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/fft.o fft.c

build/fpr.o: fpr.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/fpr.o fpr.c

build/keygen.o: keygen.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/keygen.o keygen.c

build/nist.o: nist.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/nist.o nist.c

build/nist16.o: nist16.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/nist16.o nist16.c

build/epervier16.o: epervier16.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/epervier16.o epervier16.c

build/rng.o: rng.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/rng.o rng.c

build/shake.o: shake.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/shake.o shake.c

build/sign.o: sign.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/sign.o sign.c

build/vrfy.o: vrfy.c $(HEAD1)
	$(CC) $(CFLAGS) -c -o build/vrfy.o vrfy.c

build/PQCgenKAT_sign.o: ../KAT/PQCgenKAT_sign.c $(HEAD2)
	$(CC) $(CFLAGS) -I . -DALGNAME=falcon512int -c -o build/PQCgenKAT_sign.o ../KAT/PQCgenKAT_sign.c

build/PQCgenKAT_sign_zknox.o: ../KAT/PQCgenKAT_sign_zknox.c $(HEAD2)
	$(CC) $(CFLAGS) -I . -DALGNAME=falcon512int -c -o build/PQCgenKAT_sign_zknox.o ../KAT/PQCgenKAT_sign_zknox.c
	
build/PQCgenKAT_sign_epervier_zknox.o: ../KAT/PQCgenKAT_sign_epervier_zknox.c $(HEAD2)
	$(CC) $(CFLAGS) -I . -DALGNAME=falcon512int -c -o build/PQCgenKAT_sign_epervier_zknox.o ../KAT/PQCgenKAT_sign_epervier_zknox.c
	
build/katrng.o: ../KAT/katrng.c $(HEAD2)
	$(CC) $(CFLAGS) -I . -c -o build/katrng.o ../KAT/katrng.c
